version: "2"

linters:
  default: none
  enable:
    - atomic
    - builtin_name
    - channel_size
    - container_capacity
    - container_copy
    - decl_group
    - defer_clean
    - else_unnecessary
    - embed_public
    - enum_start
    - error_name
    - error_once
    - error_type
    - error_wrap
    - exit_main
    - exit_once
    - function_name
    - function_order
    - functional_option
    - global_decl
    - global_mut
    - global_name
    - goroutine_exit
    - goroutine_forget
    - goroutine_init
    - import_alias
    - import_group
    - init
    - interface_compliance
    - interface_pointer
    - interface_receiver
    - line_length
    - map_init
    - mutex_zero_value
    - nest_less
    - no_panic
    - package_name
    - param_naked
    - printf_const
    - printf_name
    - slice_nil
    - strconv
    - string_byte_slice
    - string_escape
    - struct_embed
    - struct_field_key
    - struct_field_zero
    - struct_pointer
    - struct_tag
    - struct_zero
    - table_less_complex
    - time_usage
    - todo
    - type_assert
    - var_decl
    - var_scope

linters-settings:
  custom:
    uber-go-lint-style:
      type: "module"
      description: "Uber Go style guide linter"
      original-url: "github.com/beltranaceves/uber-go-lint-style"
      # Disabled rules provided as YAML text. By default exclude TodoRule.
      disabled_rules_yaml: |
        - TodoRule
